tasks:
  build:
    desc: Build the documentation.
    cmds:
      - docker compose run --rm documentation bun vitepress build

  check:
    desc: Check everything.
    cmds:
      - task: check-formatting
      - task: check-linting

  check-formatting:
    desc: Check formatting.
    cmds:
      - docker compose run --rm documentation bun oxfmt --check {{.CLI_ARGS}}

  check-linting:
    desc: Check linting.
    cmds:
      - docker compose run --rm documentation bun oxlint --deny-warnings

  fetch-openapi-specification:
    desc: Fetch the OpenAPI specification.
    cmds:
      - docker compose run --rm documentation sh -c "
        mkdir --parents .temporary &&
        rm -fr .temporary/server &&
        git clone --depth 1 https://github.com/squiglink/server.git .temporary/server &&
        cd .temporary/server &&
        bun install &&
        cp .env.example .env &&
        bun scripts/generate-openapi.ts &&
        mkdir --parents /documentation/public &&
        cp output/openapi.json /documentation/public/openapi.json &&
        cd /documentation &&
        rm -fr .temporary/server
        "

  fix-formatting:
    desc: Fix formatting.
    cmds:
      - docker compose run --rm documentation bun oxfmt --write {{.CLI_ARGS}}

  preview:
    desc: Preview the built documentation.
    cmds:
      - docker compose run --rm --service-ports documentation bun vitepress preview

  install-dependencies:
    desc: Install dependencies.
    cmds:
      - docker compose run --rm documentation bun install

  list:
    aliases:
      - default
    desc: List available tasks.
    cmds:
      - task --list

  setup:
    desc: Setup the application.
    cmds:
      - task: fetch-openapi-specification
      - task: install-dependencies

  start:
    desc: Start the application.
    cmds:
      - docker compose up

version: 3
